-- MySQL Script generated by MySQL Workbench
-- Tue Sep  7 17:38:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema battlenet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema battlenet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `battlenet` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `battlenet` ;

-- -----------------------------------------------------
-- Table `battlenet`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlenet`.`tipo_usuario` (
  `tipo_usuario_id` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipo_usuario_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `battlenet`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlenet`.`usuarios` (
  `usuarioid` INT NOT NULL AUTO_INCREMENT,
  `contraseña` VARCHAR(45) NOT NULL,
  `nombreusuario` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `rol` INT NOT NULL,
  `fechacreacion` DATETIME NOT NULL,
  PRIMARY KEY (`usuarioid`),
  INDEX `tipo_usuario_idx` (`rol` ASC) VISIBLE,
  CONSTRAINT `rol_id`
    FOREIGN KEY (`rol`)
    REFERENCES `battlenet`.`tipo_usuario` (`tipo_usuario_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `battlenet`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlenet`.`compras` (
  `comprasid` INT NOT NULL AUTO_INCREMENT,
  `usuarioid` INT NOT NULL,
  PRIMARY KEY (`comprasid`),
  INDEX `fk_compra_usuario_idx` (`usuarioid` ASC) VISIBLE,
  CONSTRAINT `fk_compra_usuario`
    FOREIGN KEY (`usuarioid`)
    REFERENCES `battlenet`.`usuarios` (`usuarioid`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `battlenet`.`juegos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlenet`.`juegos` (
  `juegoid` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `like` INT NOT NULL,
  `dislike` INT NOT NULL,
  `creadorid` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`juegoid`),
  INDEX `fkjuegos_usuario_idx` (`creadorid` ASC) VISIBLE,
  INDEX `fk_usuario_juego_idx` (`creadorid` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_juego`
    FOREIGN KEY (`creadorid`)
    REFERENCES `battlenet`.`usuarios` (`usuarioid`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `battlenet`.`notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlenet`.`notificaciones` (
  `notification_id` INT NOT NULL AUTO_INCREMENT,
  `mensaje` VARCHAR(300) NOT NULL,
  `fecha_publicacion` DATETIME NOT NULL,
  PRIMARY KEY (`notification_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `battlenet`.`descuentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlenet`.`descuentos` (
  `descuentos_id` INT NOT NULL AUTO_INCREMENT,
  `juego_id` INT NOT NULL,
  `notificacion_id` INT NOT NULL,
  `coeficiente` FLOAT NOT NULL,
  PRIMARY KEY (`descuentos_id`),
  INDEX `juego_id_idx` (`juego_id` ASC) VISIBLE,
  INDEX `notificacion_id_idx` (`notificacion_id` ASC) VISIBLE,
  CONSTRAINT `juego_id`
    FOREIGN KEY (`juego_id`)
    REFERENCES `battlenet`.`juegos` (`juegoid`),
  CONSTRAINT `notificacion_id`
    FOREIGN KEY (`notificacion_id`)
    REFERENCES `battlenet`.`notificaciones` (`notification_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `battlenet`.`detalles_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlenet`.`detalles_compras` (
  `detalle_compra_id` INT NOT NULL AUTO_INCREMENT,
  `juegoid` INT NOT NULL,
  `compra_id` INT NOT NULL,
  PRIMARY KEY (`detalle_compra_id`),
  INDEX `FK_juego_detalles_compra_idx` (`juegoid` ASC) VISIBLE,
  INDEX `FK_detalle_compra_idx` (`compra_id` ASC) VISIBLE,
  CONSTRAINT `FK_detalle_compra`
    FOREIGN KEY (`compra_id`)
    REFERENCES `battlenet`.`compras` (`comprasid`),
  CONSTRAINT `FK_juego_detalles_compra`
    FOREIGN KEY (`juegoid`)
    REFERENCES `battlenet`.`juegos` (`juegoid`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `battlenet`.`notificacion_tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlenet`.`notificacion_tipo_usuario` (
  `notificacion_tipo_usuario_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario_id` INT NOT NULL,
  `notificacion_id` INT NOT NULL,
  PRIMARY KEY (`notificacion_tipo_usuario_id`),
  INDEX `FK _tipo_usuario_idx` (`tipo_usuario_id` ASC) VISIBLE,
  INDEX `FK_notificacion_idx` (`notificacion_id` ASC) VISIBLE,
  CONSTRAINT `FK _tipo_usuario`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `battlenet`.`tipo_usuario` (`tipo_usuario_id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_notificacion`
    FOREIGN KEY (`notificacion_id`)
    REFERENCES `battlenet`.`notificaciones` (`notification_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `battlenet`.`tipo_puntuacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlenet`.`tipo_puntuacion` (
  `puntuacion_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_de_puntuacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`puntuacion_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `battlenet`.`puntuaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlenet`.`puntuaciones` (
  `id_puntuaciones` INT NOT NULL AUTO_INCREMENT,
  `juego_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `fechahora` VARCHAR(30) NOT NULL,
  `liketype` INT NOT NULL,
  PRIMARY KEY (`id_puntuaciones`),
  INDEX `tipo_puntuacion_idx` (`liketype` ASC) VISIBLE,
  CONSTRAINT `tipo_puntuacion_id`
    FOREIGN KEY (`liketype`)
    REFERENCES `battlenet`.`tipo_puntuacion` (`puntuacion_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `battlenet` ;

-- -----------------------------------------------------
-- procedure get_compras_usuario
-- -----------------------------------------------------

DELIMITER $$
USE `battlenet`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `get_compras_usuario`(in USUARIO_ID INT)
BEGIN	
	SELECT 
		`compras`.`comprasid`,
		`compras`.`usuarioid`
	FROM `battlenet`.`compras`
	WHERE `compras`.`usuarioid` = USUARIO_ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure get_descuentos
-- -----------------------------------------------------

DELIMITER $$
USE `battlenet`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `get_descuentos`()
BEGIN
	SELECT `descuentos`.`descuentos_id`,
		`descuentos`.`juego_id`,
		`descuentos`.`notificacion_id`
	FROM `battlenet`.`descuentos`;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure get_detalle_compra
-- -----------------------------------------------------

DELIMITER $$
USE `battlenet`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `get_detalle_compra`(in COMPRA_ID INT)
BEGIN
	SELECT `detalles_compras`.`detalle_compra_id`,
		`detalles_compras`.`juegoid`,
		`detalles_compras`.`compra_id`
	FROM `battlenet`.`detalles_compras`
    WHERE `detalles_compras`.`compra_id` = COMPRA_ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure get_juego
-- -----------------------------------------------------

DELIMITER $$
USE `battlenet`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `get_juego`(in NOMBRE_JUEGO varchar(45))
BEGIN
	SELECT 
    `juegos`.`juegoid`,
    `juegos`.`nombre`,
    `juegos`.`descripcion`,
    `juegos`.`like`,
    `juegos`.`dislike`,
    `juegos`.`precio`
	FROM `battlenet`.`juegos`
    WHERE `juegos`.`nombre` like CONCAT("%", NOMBRE_JUEGO, "%");
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure get_juegos
-- -----------------------------------------------------

DELIMITER $$
USE `battlenet`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `get_juegos`()
BEGIN
	SELECT 
    `juegos`.`juegoid`,
    `juegos`.`nombre`,
    `juegos`.`descripcion`,
    `juegos`.`like`,
    `juegos`.`dislike`,
    `juegos`.`precio`,
    max(d.coeficiente)
	FROM `battlenet`.`juegos`
    left JOIN descuentos on descuentos.juego_id  = juegos.juegoid
    group by juegos.precio,juegos.nombre,juegos.descripcion,juegos.like,juegos.dislike,juegos.precio; 
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure get_notificaciones_admin
-- -----------------------------------------------------

DELIMITER $$
USE `battlenet`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `get_notificaciones_admin`(in USARIO_ROL INT)
BEGIN
	SELECT noti.`notification_id`,
		noti.`mensaje`,
		noti.`fecha_publicacion`,
        usua.nombre_tipo_usuario
	FROM `notificaciones` noti
    inner join `notificacion_tipo_usuario` tipo on noti.notification_id = tipo.notificacion_id
	inner join `tipo_usuario` usua on usua.tipo_usuario_id = tipo.tipo_usuario_id
    
	where usua.tipo_usuario_id = USARIO_ROL;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure get_todos_los_juegos
-- -----------------------------------------------------

DELIMITER $$
USE `battlenet`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `get_todos_los_juegos`()
BEGIN
SELECT 
    `juegos`.`juegoid`,
    `juegos`.`nombre`,
    `juegos`.`descripcion`,
    `juegos`.`like`,
    `juegos`.`dislike`,
    `juegos`.`precio`
	FROM `battlenet`.`juegos`;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure get_usuario
-- -----------------------------------------------------

DELIMITER $$
USE `battlenet`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `get_usuario`(in usuario_id INT)
BEGIN
	SELECT `usuarios`.`usuarioid`,
		`usuarios`.`contraseña`,
		`usuarios`.`nombreusuario`,
		`usuarios`.`fechacreacion`,
		`usuarios`.`mail`,
		`usuarios`.`rol`
	FROM `battlenet`.`usuarios`
    inner join`battlenet`.`tipo_usuario` tipo on tipo.tipo_usuario_id = usuarios.rolid
	WHERE `usuarios`.`usuarioid` = usuario_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure get_usuarios
-- -----------------------------------------------------

DELIMITER $$
USE `battlenet`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `get_usuarios`()
BEGIN
	SELECT `usuarios`.`usuarioid`,
		`usuarios`.`contraseña`,
		`usuarios`.`nombreusuario`,
		`usuarios`.`fechacreacion`,
		`usuarios`.`mail`,
		`usuarios`.`rol`
	FROM `battlenet`.`usuarios`
    inner join`battlenet`.`tipo_usuario` tipo on tipo.tipo_usuario_id = usuarios.rol;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_descuento
-- -----------------------------------------------------

DELIMITER $$
USE `battlenet`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_descuento`(in JUEGO int,in NOTIFICACION int,in COEFICIENTE int)
BEGIN
	INSERT INTO `battlenet`.`descuentos`
	(`juego_id`,
	`notificacion_id`,
	`coeficiente`)
	VALUES
	(JUEGO,
    NOTIFICACION,
    COEFICIENTE);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_juego
-- -----------------------------------------------------

DELIMITER $$
USE `battlenet`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_juego`(in NOMBRE varchar(45),in DESCRIPCION varchar(200),in LIKES int,in DISLIKE int,in CREADORid int,IN PRECIO int)
BEGIN
INSERT INTO `battlenet`.`juegos`
(
`nombre`,
`descripcion`,
`like`,
`dislike`,
`creadorid`,
`precio`)
VALUES
(
NOMBRE,
DESCRIPCION,
LIKES,
DISLIKE,
CREADORid,
PRECIO
);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_notificacion
-- -----------------------------------------------------

DELIMITER $$
USE `battlenet`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_notificacion`(in MENSAJE varchar(200),in FECHA varchar(30))
BEGIN
	INSERT INTO `battlenet`.`notificaciones`
	(`mensaje`,
	`fecha_publicacion`)
	VALUES
	(MENSAJE,
    FECHA);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_puntuacion
-- -----------------------------------------------------

DELIMITER $$
USE `battlenet`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_puntuacion`(in JUEGO_ID INT, IN USUARIO_ID INT, IN FECHAHORA DATETIME, IN LIKETYPE INT)
BEGIN
	DECLARE likes int;
        
	INSERT INTO `battlenet`.`puntuaciones`
	(`juego_id`,`usuario_id`,`fechahora`,`liketype`)
	VALUES
	(JUEGO_ID,USUARIO_ID,FECHAHORA,LIKETYPE);

    IF LIKETYPE = 1 THEN
    
      SELECT likes = `like` from juegos where juegos.juegoid;
	  SET likes = likes + 1;
      UPDATE juegos SET `like`=likes where juegos.juegoid = JUEGO_ID;
	
	END IF;
     IF LIKETYPE = 2 THEN
    
      SELECT likes = `dislike` from juegos where juegos.juegoid;
	  SET likes = likes + 1;
      UPDATE juegos SET `dislike`=likes where juegos.juegoid = JUEGO_ID;
	
	END IF;
    
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_usuario
-- -----------------------------------------------------

DELIMITER $$
USE `battlenet`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_usuario`(in CONTRASEÑA varchar(200),in NOMBREUSUARIO varchar(200),in FECHACREACION varchar(200) ,in MAIL varchar(200),IN ROL int)
BEGIN
	INSERT INTO `battlenet`.`usuarios`
	(`contraseña`,
	`nombreusuario`,
	`fechacreacion`,
	`mail`,
	`rol`)
	VALUES
	(CONTRASEÑA,
	NOMBREUSUARIO,
	FECHACRECION,
	MAIL,
	ROL);
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
